"""Fix relationships and add many-to-many for students

Revision ID: 4e0a09566a81
Revises: fc4af1f779db
Create Date: 2026-03-02 22:53:09.507076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e0a09566a81'
down_revision = 'fc4af1f779db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_path', sa.String(length=200), nullable=True))
        batch_op.drop_constraint(batch_op.f('post_student_fkey'), type_='foreignkey')
        batch_op.drop_column('student')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('post_student_fkey'), 'user', ['student'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('file_path')

    # ### end Alembic commands ###
